Remove invalid JsonSchemaGenerator c'tor
`BaseGenerator` does not implement a copy c'tor (see `code_generators.h` line 118, the comment suggests this is intentional), so this `JsonSchemaGenerator` c'tor fails to compile without optimizations.
```
ld64.lld: error: undefined symbol: flatbuffers::BaseGenerator::BaseGenerator(flatbuffers::BaseGenerator const&)
>>> referenced by /Users/tal/proj/k2dqsc.git/external/flatbuffers.git/src/idl_gen_json_schema.cpp
>>>               flatbuffers_build/CMakeFiles/flatc.dir/src/idl_gen_json_schema.cpp.o:(symbol flatbuffers::jsons::JsonSchemaGenerator::JsonSchemaGenerator(flatbuffers::BaseGenerator const&)+0x20)
```