Use libc++ not libstdc++ for clang++-14 + C++23
Because libstdc++ 10.3.0 doesn't support C++23.

This fixes the following build error:

    In file included from /home/runner/work/flatbuffers/flatbuffers/src/idl_parser.cpp:17:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/algorithm:60:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:67:
    /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_iterator.h:2618:35: error: missing 'typename' prior to dependent type name 'iterator_traits<_It>::iterator_category'
          { using iterator_category = iterator_traits<_It>::iterator_category; };
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~