C++ fixed compile error C2678 with msvc when using std::find_if on vectors In Debug mode it is checked that iterator begin is less than end therefore the operator< in class VectorIterator is needed